import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service | Flywheel Coach',
  description: 'Terms of Service for Flywheel Coach - AI-powered app building platform',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-stone-950 text-stone-300">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-stone-100 mb-2">Terms of Service</h1>
        <p className="text-stone-500 mb-8">Last updated: December 23, 2024</p>

        <div className="space-y-8 text-stone-400 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-stone-200 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Flywheel Coach (&quot;the Service&quot;), you agree to be bound by these
              Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-200 mb-3">2. Description of Service</h2>
            <p>
              Flywheel Coach is an AI-powered platform that helps users build applications by
              generating structured prompts for AI code generation tools. The Service uses
              Google&apos;s Gemini AI to assist in creating app-building workflows.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-200 mb-3">3. User Accounts</h2>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>You must sign in with a valid Google account to use the Service</li>
              <li>You are responsible for maintaining the security of your account</li>
              <li>You must provide accurate information when creating your account</li>
              <li>You must be at least 13 years old to use the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-200 mb-3">4. Acceptable Use</h2>
            <p className="mb-3">You agree NOT to use the Service to:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Generate content that is illegal, harmful, or violates third-party rights</li>
              <li>Attempt to circumvent security measures or abuse the AI systems</li>
              <li>Use automated tools to access the Service without permission</li>
              <li>Share your account credentials with others</li>
              <li>Resell or redistribute the Service without authorization</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-200 mb-3">5. Intellectual Property</h2>
            <p className="mb-3">
              <strong className="text-stone-300">Your Content:</strong> You retain ownership of the
              ideas, problems, and app concepts you input into Flywheel Coach.
            </p>
            <p>
              <strong className="text-stone-300">Generated Content:</strong> The prompts and outputs
              generated by the AI are provided for your use in building applications. You may use
              these outputs for any lawful purpose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-200 mb-3">6. Third-Party Services</h2>
            <p>
              The Service integrates with third-party services including Google Gemini, Supabase,
              and Lovable.dev. Your use of these services is subject to their respective terms of
              service and privacy policies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-200 mb-3">7. API Usage</h2>
            <p className="mb-3">
              If you connect your own Gemini API key:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>You are responsible for any costs incurred through your API key</li>
              <li>You must comply with Google&apos;s API terms of service</li>
              <li>We store your API key encrypted and use it only to make API calls on your behalf</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-200 mb-3">8. Service Availability</h2>
            <p>
              We strive to maintain high availability but do not guarantee uninterrupted access.
              The Service may be temporarily unavailable for maintenance, updates, or due to
              factors beyond our control.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-200 mb-3">9. Limitation of Liability</h2>
            <p>
              The Service is provided &quot;as is&quot; without warranties of any kind. We are not liable
              for any indirect, incidental, or consequential damages arising from your use of the
              Service. Our total liability is limited to the amount you paid for the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-200 mb-3">10. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service at any time for violation of
              these terms. You may also delete your account at any time. Upon termination, your
              right to use the Service ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-200 mb-3">11. Changes to Terms</h2>
            <p>
              We may update these Terms of Service from time to time. Continued use of the Service
              after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-200 mb-3">12. Contact</h2>
            <p>
              For questions about these Terms, contact us at:{' '}
              <a href="mailto:legal@flywheel-coach.com" className="text-teal-400 hover:text-teal-300">
                legal@flywheel-coach.com
              </a>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-stone-800">
          <Link href="/" className="text-teal-400 hover:text-teal-300">
            ← Back to Flywheel Coach
          </Link>
        </div>
      </div>
    </div>
  );
}
